[package]
authors = ["hatoo <hato2000@gmail.com>", "clia <clia@163.com>"]
categories = [
    "command-line-utilities",
    "network-programming",
    "web-programming::http-client",
    "development-tools::profiling",
]
description = "Oha WebSocket load tester."
edition = "2021"
keywords = ["cli", "load-testing", "performance", "http"]
license = "MIT"
name = "clia-oha-ws"
readme = "README.md"
repository = "https://github.com/clia/oha-ws"
version = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["rustls"]
native-tls = ["dep:native-tls", "dep:tokio-native-tls"]
rustls = ["dep:rustls", "dep:tokio-rustls", "dep:rustls-native-certs"]

[dependencies]
anyhow = "1.0.38"
average = "0.14.1"
byte-unit = "4.0.8"
clap = { version = "4.1.4", features = ["derive"] }
crossterm = "0.27"
float-ord = "0.3.1"
flume = "0.11"
futures = "0.3.12"
humantime = "2.0.0"
libc = "0.2.147"
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.16"
tokio = { version = "1.14.0", features = ["full"] }
ratatui = { version = "0.24.0", default-features = false, features = [
    "crossterm",
] }

hyper = { version = "1.0", features = ["client", "http1", "http2"] }

# native-tls
native-tls = { version = "0.2.11", features = ["alpn"], optional = true }
tokio-native-tls = { version = "0.3.0", optional = true }

# rustls
rustls = { version = "0.21.0", features = [
    "dangerous_configuration",
], optional = true }
rustls-native-certs = { version = "0.6.2", optional = true }
tokio-rustls = { version = "0.24.0", optional = true }

base64 = "0.21.0"
rand = "0.8"
hickory-resolver = "0.24.0"
rand_regex = "0.16.0"
regex-syntax = "0.7.4"
url = "2.4.0"
pin-project-lite = "0.2.13"
http-body-util = "0.1.0"
hyper-util = { version = "0.1.1", features = ["tokio"] }

[target.'cfg(unix)'.dependencies]
rlimit = "0.10.0"
jemallocator = "0.5.0"

[dev-dependencies]
assert_cmd = "2.0.2"
axum = { version = "0.7", features = ["http2"] }
bytes = "1.0"
lazy_static = "1.4.0"
regex = "1.9.6"
